# Auto-generated EN->HI disease strings
DISEASE_HI = {
    'A bacterial disease causing dark spots on leaves and fruits, making peppers look bad and reducing the price you can get at the market.': 'एक जीवाणुजन्य रोग जिसके कारण पत्तियों और फलों पर काले धब्बे पड़ जाते हैं, जिससे मिर्च खराब दिखने लगती है और बाज़ार में मिलने वाली कीमत कम हो जाती है।',
    'A bacterial disease causing small dark spots on leaves and fruits, making tomatoes unsellable at market.': 'एक जीवाणुजन्य रोग जिसके कारण पत्तियों और फलों पर छोटे-छोटे काले धब्बे हो जाते हैं, जिससे टमाटर बाजार में बिकने लायक नहीं रह जाता है।',
    'A bacterial infection creating dark spots and holes in leaves and fruits, reducing fruit quality and market price.': 'एक जीवाणु संक्रमण जो पत्तियों और फलों में काले धब्बे और छेद बनाता है, जिससे फलों की गुणवत्ता और बाजार मूल्य कम हो जाता है।',
    "A common fungal disease that creates dark ring-like spots on older leaves, reducing the plant's ability to produce good tubers underground.": 'एक सामान्य कवक रोग जो पुरानी पत्तियों पर गहरे छल्ले जैसे धब्बे बनाता है, जिससे पौधे की भूमिगत अच्छे कंद पैदा करने की क्षमता कम हो जाती है।',
    'A devastating disease that can destroy an ENTIRE potato field within just 3–5 days. This is extremely serious. Act immediately — do not wait even one day.': 'एक विनाशकारी बीमारी जो केवल 3-5 दिनों के भीतर पूरे आलू के खेत को नष्ट कर सकती है। ये बेहद गंभीर है. तुरंत कार्रवाई करें - एक दिन भी प्रतीक्षा न करें।',
    'A fungal disease common in humid and enclosed growing areas, covering the undersides of leaves with mold and causing them to dry out.': 'एक कवक रोग जो आर्द्र और बंद उगने वाले क्षेत्रों में आम है, पत्तियों के निचले हिस्से को फफूंद से ढक देता है और उन्हें सूखने का कारण बनता है।',
    'A fungal disease creating dark spots on leaves that can cause early leaf drop and weaken the vine before harvest.': 'एक कवक रोग जो पत्तियों पर काले धब्बे बनाता है जिससे पत्तियां जल्दी गिर जाती हैं और कटाई से पहले बेल कमजोर हो जाती है।',
    'A fungal disease creating long gray or tan strips on corn leaves, reducing grain fill and yield.': 'एक कवक रोग जो मकई के पत्तों पर लंबी भूरे या भूरे रंग की धारियाँ बनाता है, जिससे अनाज का भराव और उपज कम हो जाती है।',
    'A fungal disease creating round dark spots with rings on leaves and sometimes on fruits, similar in appearance to early blight.': 'एक कवक रोग जो पत्तियों और कभी-कभी फलों पर छल्ले वाले गोल काले धब्बे बनाता है, जो दिखने में अगेती झुलसा रोग के समान होते हैं।',
    'A fungal disease creating small dark spots that make leaves look burned or scorched. Weakens the plant and reduces fruit yield.': 'एक कवक रोग जो छोटे काले धब्बे बनाता है जिससे पत्तियाँ जली हुई या झुलसी हुई दिखाई देती हैं। पौधे को कमजोर कर देता है और फल की पैदावार कम कर देता है।',
    'A fungal disease spread from nearby cedar trees that creates bright orange-yellow spots on leaves.': 'एक कवक रोग आस-पास के देवदार के पेड़ों से फैलता है जो पत्तियों पर चमकीले नारंगी-पीले धब्बे बनाता है।',
    'A fungal disease that covers leaves and young fruits with a white powdery coating, weakening the plant and reducing fruit production.': 'एक कवक रोग जो पत्तियों और छोटे फलों को सफेद पाउडर जैसी परत से ढक देता है, जिससे पौधा कमजोर हो जाता है और फल का उत्पादन कम हो जाता है।',
    'A fungal disease that covers leaves with a white powder coating, weakening the plant and reducing fruit production and size.': 'एक कवक रोग जो पत्तियों को सफेद पाउडर की परत से ढक देता है, जिससे पौधा कमजोर हो जाता है और फलों का उत्पादन और आकार कम हो जाता है।',
    "A fungal disease that creates dark ring-like spots on older tomato leaves, reducing the plant's strength and fruit yield.": 'एक कवक रोग जो टमाटर की पुरानी पत्तियों पर काले छल्ले जैसे धब्बे बनाता है, जिससे पौधे की ताकत और फल की उपज कम हो जाती है।',
    'A fungal disease that creates many small circular spots on tomato leaves, starting from the bottom of the plant and moving upward if not controlled.': 'एक कवक रोग जो टमाटर की पत्तियों पर कई छोटे गोलाकार धब्बे बनाता है, जो पौधे के नीचे से शुरू होता है और नियंत्रित न होने पर ऊपर की ओर बढ़ता है।',
    'A fungal disease that creates small reddish-brown powdery bumps on corn leaves. Reduces yield in severe cases.': 'एक कवक रोग जो मक्के की पत्तियों पर छोटे-छोटे लाल-भूरे पाउडर जैसे उभार बनाता है। गंभीर मामलों में उपज कम कर देता है।',
    'A fungal disease that rots the fruit and creates purple spots on leaves. Fruits shrivel and turn completely black.': 'एक कवक रोग जो फल को सड़ा देता है और पत्तियों पर बैंगनी रंग के धब्बे बना देता है। फल सिकुड़ कर पूरी तरह काले हो जाते हैं।',
    'A fungal infection that creates dark, rough spots on leaves and fruits, making them unsellable.': 'एक कवक संक्रमण जो पत्तियों और फलों पर काले, खुरदरे धब्बे बना देता है, जिससे वे बेचने लायक नहीं रह जाते हैं।',
    'A highly destructive disease that can wipe out an ENTIRE tomato field within one week. Take urgent action TODAY.': 'एक अत्यधिक विनाशकारी बीमारी जो एक सप्ताह के भीतर पूरे टमाटर के खेत को नष्ट कर सकती है। आज ही तत्काल कार्रवाई करें.',
    'A serious fungal disease creating large cigar-shaped gray-green spots on corn leaves. Can cause heavy yield loss.': 'मक्के की पत्तियों पर सिगार के आकार के बड़े भूरे-हरे धब्बे बनाने वाला एक गंभीर कवक रोग। उपज का भारी नुकसान हो सकता है.',
    'A serious virus spread by tiny white flying insects (whiteflies). Once infected, plants stop growing and produce almost no fruit. Act quickly to protect healthy plants.': 'छोटे सफेद उड़ने वाले कीड़ों (व्हाइटफ्लाइज़) द्वारा फैलने वाला एक गंभीर वायरस। एक बार संक्रमित होने पर, पौधे बढ़ना बंद कर देते हैं और लगभग कोई फल नहीं देते हैं। स्वस्थ पौधों की सुरक्षा के लिए शीघ्रता से कार्य करें।',
    'A serious wood disease of grapevines that blocks water flow inside the vine. Trees suddenly wilt in hot weather and slowly die over years.': 'अंगूर की बेलों में होने वाली एक गंभीर लकड़ी की बीमारी जो बेल के अंदर पानी के प्रवाह को अवरुद्ध कर देती है। गर्म मौसम में पेड़ अचानक मुरझा जाते हैं और वर्षों में धीरे-धीरे मर जाते हैं।',
    'A very damaging fungal disease that turns grape berries completely black and shrivelled, making them worthless.': 'एक बहुत ही हानिकारक कवक रोग जो अंगूर के जामुनों को पूरी तरह से काला और सिकुड़ा हुआ बना देता है, जिससे वे बेकार हो जाते हैं।',
    'A virus that creates a patchy mosaic pattern on leaves and reduces fruit quality and size. This virus spreads very easily through touch.': 'एक वायरस जो पत्तियों पर धब्बेदार मोज़ेक पैटर्न बनाता है और फल की गुणवत्ता और आकार को कम कर देता है। यह वायरस छूने से बहुत आसानी से फैलता है।',
    'Add compost to the soil once a year': 'वर्ष में एक बार मिट्टी में खाद डालें',
    'Add mulch around the base to keep moisture in': 'नमी बनाए रखने के लिए आधार के चारों ओर गीली घास डालें',
    'Add nitrogen-rich fertiliser at the right growth stage': 'सही विकास अवस्था में नाइट्रोजन युक्त उर्वरक डालें',
    'Always paint pruning cuts with wound sealant right after cutting': 'काटने के तुरंत बाद हमेशा कटे हुए हिस्सों को घाव सीलेंट से पेंट करें',
    'Always wash hands with soap before working with tomato plants': 'टमाटर के पौधों के साथ काम करने से पहले हमेशा साबुन से हाथ धोएं',
    'Apple': 'सेब',
    'Apple Scab': 'सेब की पपड़ी',
    'Apply as soon as the first large spots appear': 'जैसे ही पहले बड़े धब्बे दिखाई दें, लागू करें',
    'Apply balanced fertiliser after harvest to restore tree strength': 'पेड़ों की मजबूती बहाल करने के लिए कटाई के बाद संतुलित उर्वरक डालें',
    'Apply compost around the base every spring': 'हर वसंत ऋतु में आधार के चारों ओर खाद डालें',
    'Apply mulch around the base to keep soil moist and cool': 'मिट्टी को नम और ठंडा रखने के लिए आधार के चारों ओर गीली घास लगाएं',
    'Apply nitrogen-rich fertiliser to strengthen plants — weak plants get more disease': 'पौधों को मजबूत करने के लिए नाइट्रोजन युक्त उर्वरक डालें - कमजोर पौधों को अधिक रोग लगते हैं',
    'Avoid making very large pruning wounds on old vines': 'पुरानी लताओं पर बहुत बड़े छंटाई वाले घाव बनाने से बचें',
    'Avoid overhead irrigation — use drip or furrow irrigation': 'ओवरहेड सिंचाई से बचें - ड्रिप या फ़रो सिंचाई का उपयोग करें',
    'Avoid overly dense planting — give each plant space': 'अत्यधिक सघन रोपण से बचें - प्रत्येक पौधे को जगह दें',
    'Avoid overusing nitrogen fertiliser': 'नाइट्रोजन उर्वरक का अधिक प्रयोग करने से बचें',
    'Avoid planting corn too densely': 'मक्के को बहुत सघन रूप से बोने से बचें',
    'Avoid touching healthy plants after touching sick ones — wash hands in between': 'बीमार पौधों को छूने के बाद स्वस्थ पौधों को छूने से बचें - बीच-बीच में हाथ धोते रहें',
    'Avoid watering from above': 'ऊपर से पानी देने से बचें',
    'Avoid watering from above — use drip irrigation at the base': 'ऊपर से पानी देने से बचें - आधार पर ड्रिप सिंचाई का उपयोग करें',
    'Avoid watering in the evening — water in the morning only': 'शाम को पानी देने से बचें - केवल सुबह पानी दें',
    'Avoid wetting leaves when watering': 'पानी देते समय पत्तियों को गीला करने से बचें',
    'Avoid working in the orchard when plants are wet': 'जब पौधे गीले हों तो बगीचे में काम करने से बचें',
    'Bacterial Spot': 'बैक्टीरियल स्पॉट',
    'Badly affected leaves dry out and curl up': 'बुरी तरह प्रभावित पत्तियाँ सूखकर मुड़ जाती हैं',
    'Badly infected leaves fall off the vine early': 'बुरी तरह से संक्रमित पत्तियाँ बेल से जल्दी गिर जाती हैं',
    'Begin fungicide spray before the rainy season starts': 'बरसात का मौसम शुरू होने से पहले फफूंदनाशक स्प्रे शुरू करें',
    'Bell Pepper': 'शिमला मिर्च',
    'Berries develop small dark spots and may crack open': 'जामुन में छोटे-छोटे काले धब्बे विकसित हो जाते हैं और वे फट सकते हैं',
    'Berries turn brown, then completely black and hard like a raisin': 'जामुन भूरे, फिर बिल्कुल काले और किशमिश की तरह सख्त हो जाते हैं',
    'Black Measles (Vine Disease)': 'काला खसरा (बेल रोग)',
    'Black Rot': 'काला सड़न',
    'Blueberry': 'ब्लूबेरी',
    'Bright orange or yellow spots on the top side of leaves': 'पत्तियों के ऊपरी भाग पर चमकीले नारंगी या पीले धब्बे',
    'Bumps break open and release rust-coloured powder': 'उभार टूटकर खुल जाते हैं और जंग के रंग का पाउडर छोड़ते हैं',
    'Buy certified disease-free seedlings only from a government nursery': 'प्रमाणित रोगमुक्त पौधे केवल सरकारी नर्सरी से ही खरीदें',
    'Buy certified disease-free seeds from a trusted source': 'किसी विश्वसनीय स्रोत से प्रमाणित रोग-मुक्त बीज खरीदें',
    'Buy certified disease-free seeds or seedlings': 'प्रमाणित रोग-मुक्त बीज या पौध खरीदें',
    'Buy only certified virus-free seeds': 'केवल प्रमाणित वायरस-मुक्त बीज ही खरीदें',
    'Buy virus-resistant tomato varieties — ask your seed dealer specifically': 'वायरस-प्रतिरोधी टमाटर की किस्में खरीदें - अपने बीज विक्रेता से विशेष रूप से पूछें',
    'Cedar Apple Rust': 'देवदार सेब जंग',
    'Check vines weekly during the monsoon for early signs of disease': 'रोग के शुरुआती लक्षणों के लिए मानसून के दौरान साप्ताहिक रूप से बेलों की जाँच करें',
    'Cherry': 'चेरी',
    'Choose apple varieties that resist this disease': 'सेब की ऐसी प्रजातियाँ चुनें जो इस रोग का प्रतिरोध करें',
    'Choose late blight resistant tomato varieties — ask your seed dealer': 'लेट ब्लाइट प्रतिरोधी टमाटर की किस्में चुनें - अपने बीज विक्रेता से पूछें',
    'Citrus Greening Disease': 'सिट्रस ग्रीनिंग रोग',
    'Clouds of tiny white insects fly up when you shake the plant': 'जब आप पौधे को हिलाते हैं तो छोटे सफेद कीड़ों के बादल उड़ जाते हैं',
    'Common Rust': 'सामान्य जंग',
    'Contaminated tools like knives, scissors, or stakes': 'चाकू, कैंची या डंडे जैसे दूषित उपकरण',
    'Control the psyllid insect very aggressively on all remaining healthy trees using approved insecticide': 'अनुमोदित कीटनाशक का उपयोग करके शेष सभी स्वस्थ पेड़ों पर साइलीड कीट को बहुत आक्रामक तरीके से नियंत्रित करें',
    'Control weeds in the early growth stages when plants are still small': 'जब पौधे अभी छोटे हों तो विकास की प्रारंभिक अवस्था में ही खरपतवारों पर नियंत्रण रखें',
    'Cool and wet weather (10–20°C with rain, fog, or heavy dew)': 'ठंडा और गीला मौसम (बारिश, कोहरे या भारी ओस के साथ 10-20 डिग्री सेल्सियस)',
    'Cool nights and warm days with high humidity': 'उच्च आर्द्रता के साथ ठंडी रातें और गर्म दिन',
    'Cool nights followed by warm days': 'ठंडी रातें और उसके बाद गर्म दिन',
    'Cool, wet weather (15–20°C) with rain or heavy dew — spreads extremely fast': 'बारिश या भारी ओस के साथ ठंडा, गीला मौसम (15-20 डिग्री सेल्सियस) - बहुत तेजी से फैलता है',
    'Corn (Maize)': 'मक्का (मक्का)',
    'Corn planted very close together without space': 'मक्के को बिना जगह के बहुत पास-पास बोया गया',
    'Cover seedlings with insect-proof nets until they are well established': 'जब तक अंकुर अच्छी तरह स्थापित न हो जाएं तब तक उन्हें कीट-रोधी जाल से ढकें',
    'Cut and remove all dead or diseased branches immediately': 'सभी मृत या रोगग्रस्त शाखाओं को तुरंत काटें और हटा दें',
    'Cut back to healthy white wood and paint wounds with copper paste or tree wound sealant': 'स्वस्थ सफेद लकड़ी को काटें और घावों को तांबे के पेस्ट या पेड़ के घाव सीलेंट से पेंट करें',
    'Dark brown irregular spots on leaves': 'पत्तियों पर गहरे भूरे रंग के अनियमित धब्बे',
    'Dark brown spots with concentric rings (like a dartboard target) starting on older lower leaves': 'पुरानी निचली पत्तियों पर शुरू होने वाले गाढ़े छल्ले (डार्टबोर्ड लक्ष्य की तरह) वाले गहरे भूरे रंग के धब्बे',
    'Dark brown spots with rings inside — like a target or dartboard — on older lower leaves': 'पुरानी निचली पत्तियों पर अंदर छल्ले वाले गहरे भूरे रंग के धब्बे - लक्ष्य या डार्टबोर्ड की तरह',
    'Dark olive-green or brown spots on leaves': 'पत्तियों पर गहरे जैतून-हरे या भूरे रंग के धब्बे',
    'Dark sunken spots may also appear on fruits near the stem': 'तने के पास फलों पर गहरे धंसे हुए धब्बे भी दिखाई दे सकते हैं',
    'Dark, raised or sunken spots on the pepper fruits themselves': 'काली मिर्च के फलों पर गहरे, उभरे हुए या धँसे हुए धब्बे',
    'Dark, raised spots on green fruits': 'हरे फलों पर गहरे, उभरे हुए धब्बे',
    'Dead or wounded branches left on the tree': 'पेड़ पर बची मृत या घायल शाखाएँ',
    'Dense planting that traps moisture between plants': 'घना रोपण जो पौधों के बीच नमी को फँसाता है',
    'Dense planting with poor airflow between plants': 'पौधों के बीच खराब वायु प्रवाह के साथ घना रोपण',
    'Disease in the air from nearby infected fields can reach your farm': 'आस-पास के संक्रमित खेतों से हवा में मौजूद रोग आपके खेत तक पहुँच सकते हैं',
    'Disinfect pruning tools between every plant with bleach water': 'प्रत्येक पौधे के बीच के छंटाई उपकरणों को ब्लीच वाले पानी से कीटाणुरहित करें',
    'Do NOT leave infected material in the field, compost it, or throw near water sources': 'संक्रमित सामग्री को खेत में न छोड़ें, उससे खाद न बनाएं, या जल स्रोतों के पास न फेंकें',
    'Do not grow peppers in the same spot every year — rotate with other crops': 'हर साल एक ही स्थान पर मिर्च न उगाएं - अन्य फसलों के साथ बारी-बारी से उगाएं',
    'Do not smoke near tomato plants — tobacco carries a related virus': 'टमाटर के पौधों के पास धूम्रपान न करें - तम्बाकू में संबंधित वायरस होता है',
    'Do not wait until infection spreads to many leaves': 'तब तक इंतजार न करें जब तक संक्रमण कई पत्तियों तक न फैल जाए',
    'Do not work in the field when leaves are still wet with dew or rain': 'जब पत्ते अभी भी ओस या बारिश से गीले हों तो खेत में काम न करें',
    'Dry weather with high humidity — common when nights get cooler': 'उच्च आर्द्रता के साथ शुष्क मौसम - आम बात है जब रातें ठंडी हो जाती हैं',
    'Dry weather with warm days and cool nights': 'गर्म दिन और ठंडी रातों के साथ शुष्क मौसम',
    'Early Blight': 'प्रारंभिक तुषार',
    'Earth up soil around stems as plants grow to protect tubers from sunlight': 'जैसे-जैसे पौधे बढ़ते हैं, कंदों को धूप से बचाने के लिए तनों के चारों ओर मिट्टी चढ़ा दें',
    'Ensure good drainage so water does not pool in the field': 'अच्छी जल निकासी सुनिश्चित करें ताकि पानी खेत में जमा न हो',
    'Ensure good drainage so water does not stand in the field': 'अच्छी जल निकासी सुनिश्चित करें ताकि पानी खेत में जमा न हो',
    'Excess nitrogen fertiliser makes plants soft and very attractive to mites': 'अतिरिक्त नाइट्रोजन उर्वरक पौधों को मुलायम और घुन के लिए बहुत आकर्षक बनाता है',
    'Farmers working in wet fields spread bacteria on hands and tools': 'गीले खेतों में काम करने वाले किसानों के हाथों और औजारों पर बैक्टीरिया फैलते हैं',
    'Feed plants regularly with balanced fertiliser throughout the season': 'पूरे मौसम में पौधों को नियमित रूप से संतुलित उर्वरक खिलाएं',
    'Feed with balanced fertiliser after each harvest': 'प्रत्येक कटाई के बाद संतुलित उर्वरक खिलाएं',
    'Feed with potassium-rich fertiliser during fruiting for bigger, better peppers': 'बड़ी, बेहतर मिर्च के लिए फलने के दौरान पोटेशियम युक्त उर्वरक खिलाएं',
    'Feed with potassium-rich fertiliser during the fruiting stage for better quality fruits': 'बेहतर गुणवत्ता वाले फलों के लिए फल लगने की अवस्था के दौरान पोटेशियम युक्त उर्वरक खिलाएं',
    'Fine yellow or white speckling all over leaves — looks like someone threw dust or sand on them': 'पूरी पत्तियों पर महीन पीले या सफेद धब्बे - ऐसा लगता है जैसे किसी ने उन पर धूल या रेत फेंक दी हो',
    'Fruits develop brown rings that spread and turn black': 'फलों पर भूरे रंग के छल्ले बन जाते हैं जो फैलकर काले हो जाते हैं',
    'Fruits develop large dark brown patches and rot quickly': 'फलों पर बड़े गहरे भूरे रंग के धब्बे बन जाते हैं और वे जल्दी सड़ जाते हैं',
    'Fruits may crack or not grow properly': 'फल फट सकते हैं या ठीक से विकसित नहीं हो सकते',
    'Fruits may develop pale spots': 'फलों पर पीले धब्बे विकसित हो सकते हैं',
    'Fruits may show yellow patches or be smaller than normal': 'फलों पर पीले धब्बे दिखाई दे सकते हैं या सामान्य से छोटे हो सकते हैं',
    'Fungal spores in infected soil and old crop waste left in the field': 'संक्रमित मिट्टी में फफूंद के बीजाणु और खेत में बचा हुआ पुराना फसल अपशिष्ट',
    'Fungus living inside the old wood of the vine': 'बेल की पुरानी लकड़ी के अंदर रहने वाला कवक',
    'Fungus travels from nearby juniper or cedar trees via wind': 'कवक पास के जुनिपर या देवदार के पेड़ों से हवा के माध्यम से फैलता है',
    'Grape': 'अंगूर',
    'Gray Leaf Spot': 'ग्रे लीफ स्पॉट',
    'Grow tomatoes in well-ventilated open areas when possible': 'जब संभव हो तो टमाटरों को अच्छी तरह हवादार खुले क्षेत्रों में उगाएं',
    'Growing corn in the same field every year': 'हर साल एक ही खेत में मक्का उगाना',
    'Growing the same crop every year in the same field': 'हर साल एक ही खेत में एक ही फसल उगाना',
    'Growing tomatoes in the same location year after year': 'साल दर साल एक ही स्थान पर टमाटर उगाना',
    'Harvest when the vines naturally die back on their own': 'जब लताएँ स्वाभाविक रूप से अपने आप मर जाएँ तब कटाई करें',
    'Healthy Plant': 'स्वस्थ पौधा',
    "Heavily infected leaves die early, reducing the plant's ability to ripen fruits": 'अत्यधिक संक्रमित पत्तियाँ जल्दी मर जाती हैं, जिससे पौधे की फलों को पकाने की क्षमता कम हो जाती है',
    'Heavily infected leaves turn yellow and fall off': 'अत्यधिक संक्रमित पत्तियां पीली होकर गिर जाती हैं',
    'High humidity without rain': 'बारिश के बिना उच्च आर्द्रता',
    'Hot and dry weather (above 30°C) causes rapid multiplication': 'गर्म और शुष्क मौसम (30 डिग्री सेल्सियस से ऊपर) तेजी से प्रजनन का कारण बनता है',
    'If more than 30% of the crop is infected, consider harvesting tubers early to save what remains': 'यदि 30% से अधिक फसल संक्रमित है, तो बचे हुए हिस्से को बचाने के लिए कंदों की जल्दी कटाई करने पर विचार करें',
    'Improve airflow by thinning out crowded plants': 'भीड़भाड़ वाले पौधों को पतला करके वायु प्रवाह में सुधार करें',
    'Improve airflow by thinning out dense vine growth': 'घनी बेलों की वृद्धि को कम करके वायु प्रवाह में सुधार करें',
    'Improve spacing between plants for better air movement': 'बेहतर वायु संचलन के लिए पौधों के बीच दूरी बढ़ाएँ',
    'Improve ventilation immediately — open vents or increase spacing between plants': 'वेंटिलेशन में तुरंत सुधार करें - वेंट खोलें या पौधों के बीच दूरी बढ़ाएँ',
    'Infected fallen leaves from last season left in the field': 'पिछले सीज़न की संक्रमित गिरी हुई पत्तियाँ खेत में छोड़ दी गईं',
    'Infected leaves dry and fall off, starting from the bottom of the plant upward': 'संक्रमित पत्तियाँ पौधे के नीचे से शुरू होकर ऊपर की ओर सूखकर गिर जाती हैं',
    'Infected leaves dry out and fall off, reducing fruit production': 'संक्रमित पत्तियाँ सूखकर गिर जाती हैं, जिससे फल उत्पादन कम हो जाता है',
    'Infected mummified berries left on the vine from last year': 'पिछले वर्ष से संक्रमित ममीकृत जामुन बेल पर बचे हैं',
    'Infected older leaves spreading spores to new leaves': 'संक्रमित पुरानी पत्तियाँ बीजाणुओं को नई पत्तियों में फैलाती हैं',
    'Infected planting material brought from outside your farm': 'आपके खेत के बाहर से लाई गई संक्रमित रोपण सामग्री',
    'Infected seed potatoes planted from last year': 'पिछले वर्ष लगाए गए संक्रमित बीज आलू',
    'Infected seeds or seedlings brought from outside your farm': 'आपके खेत के बाहर से लाए गए संक्रमित बीज या पौधे',
    'Infected seeds planted at the start of the season': 'मौसम की शुरुआत में लगाए गए संक्रमित बीज',
    'Insects causing wounds on the fruit where fungus enters': 'कीड़े फल पर घाव पैदा करते हैं जहां कवक प्रवेश करता है',
    'Inspect your orchard every week — catch it early': 'हर सप्ताह अपने बगीचे का निरीक्षण करें - इसे जल्दी पकड़ें',
    'Keep fallen leaves cleaned up around the tree': 'पेड़ के चारों ओर गिरी हुई पत्तियों को साफ रखें',
    'Keep soil evenly moist — potato tubers crack if soil dries and wets in cycles': 'मिट्टी को समान रूप से नम रखें - यदि मिट्टी सूखती है और चक्रों में गीली होती है तो आलू के कंद फट जाते हैं',
    'Keep the base of plants clear of fallen leaves': 'पौधों के आधार को गिरी हुई पत्तियों से साफ़ रखें',
    'Keep the bed weed-free around plants': 'पौधों के चारों ओर क्यारी को खरपतवार मुक्त रखें',
    'Keep the orchard clean of fallen fruits and leaves': 'बगीचे को गिरे हुए फलों और पत्तियों से साफ रखें',
    'Keep the vineyard floor clean of fallen leaves': 'अंगूर के बगीचे के फर्श को गिरी हुई पत्तियों से साफ रखें',
    'Keep watering regularly at the base of the tree': 'पेड़ के आधार पर नियमित रूप से पानी देते रहें',
    'Keep weeds away from the crop': 'खरपतवारों को फसल से दूर रखें',
    'Large, dark, water-soaked patches on leaves — appearing suddenly and spreading fast': 'पत्तियों पर बड़े, काले, पानी से लथपथ धब्बे - अचानक प्रकट होते हैं और तेजी से फैलते हैं',
    'Large, dark, water-soaked spots on leaves that appear suddenly': 'पत्तियों पर बड़े, काले, पानी से लथपथ धब्बे जो अचानक दिखाई देते हैं',
    'Large, long gray-green or tan spots shaped like a cigar on leaves': 'पत्तियों पर सिगार के आकार के बड़े, लंबे भूरे-हरे या भूरे रंग के धब्बे',
    'Late Blight': 'आलू और टमाटर के पौधों में होने वाली एक बीमारी',
    'Leaf Blight': 'पत्ती का झुलसा रोग',
    'Leaf Mold': 'पत्ती का साँचा',
    'Leaf Scorch': 'पत्ती झुलसना',
    'Leaves curl and become twisted': 'पत्तियाँ मुड़ जाती हैं और मुड़ जाती हैं',
    'Leaves curl strongly upward and turn pale yellow-green': 'पत्तियां मजबूती से ऊपर की ओर मुड़ जाती हैं और हल्के पीले-हरे रंग में बदल जाती हैं',
    'Leaves look distorted, curled, or wrinkled': 'पत्तियाँ विकृत, मुड़ी हुई या झुर्रीदार दिखती हैं',
    'Leaves look very small, crinkled, and distorted': 'पत्तियाँ बहुत छोटी, झुर्रीदार और विकृत दिखती हैं',
    'Leaves may drop early, weakening the tree': 'पत्तियाँ जल्दी गिर सकती हैं, जिससे पेड़ कमजोर हो जाएगा',
    'Leaves may turn yellow and fall early': 'पत्तियाँ पीली पड़ सकती हैं और जल्दी गिर सकती हैं',
    'Leaves suddenly wilt and dry out completely on hot days': 'गर्म दिनों में पत्तियाँ अचानक मुरझा जाती हैं और पूरी तरह सूख जाती हैं',
    'Leaves turn bronze or brown, then dry out completely': 'पत्तियाँ कांस्य या भूरे रंग की हो जाती हैं, फिर पूरी तरह सूख जाती हैं',
    'Leaves turn yellow on one side of the branch while other side stays green': 'शाखा के एक तरफ की पत्तियाँ पीली हो जाती हैं जबकि दूसरी तरफ हरी रहती हैं',
    'Leaves turn yellow under the white patches': 'सफेद धब्बों के नीचे पत्तियाँ पीली हो जाती हैं',
    'Light and dark green mosaic or mottled patchwork pattern on leaves': 'पत्तियों पर हल्का और गहरा हरा मोज़ेक या धब्बेदार पैचवर्क पैटर्न',
    'Long, narrow gray or tan coloured patches on leaves': 'पत्तियों पर लंबे, संकीर्ण भूरे या भूरे रंग के धब्बे',
    'Lower leaves affected first — disease moves upward if not treated': 'निचली पत्तियाँ पहले प्रभावित होती हैं - उपचार न करने पर रोग ऊपर की ओर बढ़ता है',
    'Lower leaves die and fall off first': 'निचली पत्तियाँ पहले मर कर गिर जाती हैं',
    'Make sure the crop gets enough fertiliser — strong healthy plants fight disease better': 'सुनिश्चित करें कि फसल को पर्याप्त उर्वरक मिले - मजबूत स्वस्थ पौधे बीमारी से बेहतर ढंग से लड़ते हैं',
    'Many small, round spots with dark edges and lighter centres on leaves': 'पत्तियों पर गहरे किनारे और हल्के केंद्र वाले कई छोटे, गोल धब्बे',
    'Moderate temperatures and wet or humid weather for long periods': 'मध्यम तापमान और लंबे समय तक गीला या आर्द्र मौसम',
    'Mosaic Virus': 'मोज़ेक वायरस',
    'Mulch the soil around plants to reduce soil splash onto leaves': 'पत्तियों पर मिट्टी के छींटे कम करने के लिए पौधों के चारों ओर की मिट्टी को मल्च करें',
    'Mulch the soil around plants to stop rain from splashing spores onto leaves': 'बारिश से बीजाणुओं को पत्तियों पर गिरने से रोकने के लिए पौधों के चारों ओर की मिट्टी को गीला कर दें',
    'Neem oil spray (5 ml per litre of water) works well for organic farmers — spray every 5 days': 'नीम तेल स्प्रे (5 मिली प्रति लीटर पानी) जैविक किसानों के लिए अच्छा काम करता है - हर 5 दिन में स्प्रे करें',
    'Neem oil spray (organic option) every 5 days': 'हर 5 दिन में नीम तेल स्प्रे (जैविक विकल्प)।',
    'Never water from above — water at the base of the tree only': 'कभी भी ऊपर से पानी न डालें - पेड़ के नीचे ही पानी दें',
    'No complete cure exists — manage by removing infected wood': 'कोई पूर्ण इलाज मौजूद नहीं है - संक्रमित लकड़ी को हटाकर प्रबंधन करें',
    'No cure for virus-infected plants — remove and burn infected plants away from the field': 'वायरस से संक्रमित पौधों का कोई इलाज नहीं - संक्रमित पौधों को खेत से दूर हटा दें और जला दें',
    'Northern Leaf Blight': 'उत्तरी पत्ती का झुलसा रोग',
    'Old vines (10+ years) are most vulnerable': 'पुरानी लताएँ (10+ वर्ष) सबसे अधिक असुरक्षित होती हैं',
    'Olive-green to grayish-brown mold growth on the UNDERSIDE of leaves': 'पत्तियों के नीचे जैतून-हरे से लेकर भूरे-भूरे रंग की फफूंद का विकास',
    'One of the most deadly citrus diseases in the world. Trees produce small, bitter, green fruits and slowly die. There is NO cure — act fast to protect your other trees.': 'दुनिया में सबसे घातक साइट्रस रोगों में से एक। पेड़ छोटे, कड़वे, हरे फल पैदा करते हैं और धीरे-धीरे मर जाते हैं। इसका कोई इलाज नहीं है - अपने अन्य पेड़ों की सुरक्षा के लिए तेजी से कार्य करें।',
    'Orange / Citrus': 'नारंगी/खट्टे',
    'Pale yellow-green patches on the upper surface of leaves': 'पत्तियों की ऊपरी सतह पर हल्के पीले-हरे धब्बे',
    'Patches have straight edges and run along the leaf veins': 'पैच के किनारे सीधे होते हैं और पत्ती की शिराओं के साथ चलते हैं',
    'Peach': 'आड़ू',
    'Place yellow sticky traps throughout the field to catch whiteflies early': 'सफेद मक्खियों को जल्दी पकड़ने के लिए पूरे खेत में पीले चिपचिपे जाल लगाएं',
    'Plant disease-resistant corn varieties': 'रोग प्रतिरोधी मक्के की किस्में लगाएं',
    'Plant early in the season to avoid peak rust periods': 'जंग की चरम अवधि से बचने के लिए मौसम की शुरुआत में पौधे लगाएं',
    'Plant growth completely stops': 'पौधों का विकास पूर्णतः रुक जाता है',
    'Plant in raised beds for better water drainage': 'बेहतर जल निकासी के लिए ऊंची क्यारियों में पौधे लगाएं',
    'Plant mildew-resistant varieties if available in your area': 'यदि आपके क्षेत्र में फफूंदी प्रतिरोधी किस्में उपलब्ध हों तो पौधे लगाएं',
    'Plant only certified blight-free seed potatoes from a government supplier': 'केवल सरकारी आपूर्तिकर्ता से प्रमाणित ब्लाइट-मुक्त बीज आलू ही रोपें',
    'Plant resistant peach varieties if available in your area': 'यदि आपके क्षेत्र में आड़ू की प्रतिरोधी किस्में उपलब्ध हों तो पौधे लगाएं',
    'Plant rust-resistant apple varieties': 'जंग प्रतिरोधी सेब की किस्में लगाएं',
    'Plant rust-resistant hybrid corn varieties': 'जंग प्रतिरोधी संकर मकई की किस्में लगाएं',
    'Plants crowded together without space for airflow': 'हवा के प्रवाह के लिए जगह न होने के कारण पौधे आपस में भीड़ गए',
    'Plants lacking nutrition — especially nitrogen fertiliser': 'पौधों में पोषण की कमी है - विशेषकर नाइट्रोजन उर्वरक की',
    'Plants weakened from lack of water or nutrients': 'पानी या पोषक तत्वों की कमी से पौधे कमजोर हो गए',
    'Poor airflow between crowded plants': 'भीड़-भाड़ वाले पौधों के बीच ख़राब वायु प्रवाह',
    'Poor airflow in the vineyard': 'अंगूर के बगीचे में ख़राब वायु प्रवाह',
    'Poor ventilation in enclosed or polyhouse growing': 'बंद कमरे या पॉलीहाउस में खराब वेंटिलेशन',
    'Potato': 'आलू',
    'Powdery Mildew': 'पाउडर रूपी फफूंद',
    'Problem gets much worse in hot, dry weather': 'गर्म, शुष्क मौसम में समस्या और भी बदतर हो जाती है',
    'Protect fruits from insect damage': 'फलों को कीड़ों से होने वाले नुकसान से बचाएं',
    'Prune branches so air flows freely through the tree': 'शाखाओं की छँटाई करें ताकि हवा पेड़ के माध्यम से स्वतंत्र रूप से प्रवाहित हो सके',
    'Prune dead branches every winter': 'प्रत्येक शीतकाल में मृत शाखाओं की छँटाई करें',
    'Prune during dry weather — never during rain': 'शुष्क मौसम के दौरान छँटाई करें - बारिश के दौरान कभी नहीं',
    'Prune every year to maintain good vine shape': 'बेल का अच्छा आकार बनाए रखने के लिए हर साल छँटाई करें',
    'Prune infected shoot tips and destroy them by burning': 'संक्रमित प्ररोहों के शीर्षों की छँटाई करें और उन्हें जलाकर नष्ट कर दें',
    'Prune old branches after harvest': 'कटाई के बाद पुरानी शाखाओं की छँटाई करें',
    'Prune the tree every year to remove dead wood': 'मृत लकड़ी को हटाने के लिए हर साल पेड़ की छंटाई करें',
    'Prune the tree to open up the centre': 'केंद्र को खोलने के लिए पेड़ की छँटाई करें',
    'Pruning wounds left exposed without protection': 'कांट-छांट के घावों को बिना सुरक्षा के खुला छोड़ दिया गया',
    'Pruning wounds left open': 'घावों को काटकर खुला छोड़ दिया गया',
    'Purple spots on leaves with brown centres': 'पत्तियों पर भूरे मध्य भाग वाले बैंगनी धब्बे',
    'Rain and wind spreading bacteria from plant to plant': 'बारिश और हवा से पौधे से पौधे तक बैक्टीरिया फैल रहे हैं',
    'Rain splashing spores from soil up onto leaves': 'बारिश से बीजाणु मिट्टी से निकलकर पत्तियों पर गिर रहे हैं',
    'Raspberry': 'रसभरी',
    'Remove ALL infected plant parts from the field and BURN them far away — do not compost or leave in field': 'खेत से सभी संक्रमित पौधों के हिस्सों को हटा दें और उन्हें दूर जला दें - खाद न बनाएं या खेत में न छोड़ें',
    'Remove ALL infected plants from the field immediately and burn them far away from your crops': 'सभी संक्रमित पौधों को तुरंत खेत से हटा दें और उन्हें अपनी फसल से दूर जला दें',
    'Remove all dead plant material before the new season starts': 'नया मौसम शुरू होने से पहले सभी मृत पौधों को हटा दें',
    'Remove all mummified berries from the vine and the ground': 'सभी ममीकृत जामुनों को बेल और जमीन से हटा दें',
    'Remove all rotted fruits from the tree and ground and burn them': 'सभी सड़े-गले फलों को पेड़ से उतारकर पीस लें और जला दें',
    'Remove and burn all fallen leaves to stop the disease from spreading next year': 'अगले वर्ष बीमारी को फैलने से रोकने के लिए सभी गिरी हुई पत्तियों को हटा दें और जला दें',
    'Remove and burn badly affected leaves': 'बुरी तरह प्रभावित पत्तियों को हटा दें और जला दें',
    'Remove and burn badly infected plants from the field': 'बुरी तरह संक्रमित पौधों को खेत से निकालकर जला दें',
    'Remove and destroy all infected leaves starting from the bottom of the plant': 'पौधे के नीचे से शुरू करके सभी संक्रमित पत्तियों को हटा दें और नष्ट कर दें',
    'Remove and destroy badly infected leaves': 'बुरी तरह से संक्रमित पत्तियों को हटा कर नष्ट कर दें',
    'Remove and destroy fallen infected leaves': 'गिरी हुई संक्रमित पत्तियों को हटा कर नष्ट कर दें',
    'Remove and destroy infected leaves from the plants': 'पौधों से संक्रमित पत्तियों को निकालकर नष्ट कर दें',
    'Remove and destroy infected plants IMMEDIATELY — before whiteflies spread the virus to more plants': 'संक्रमित पौधों को तुरंत हटाएं और नष्ट कर दें - इससे पहले कि सफेद मक्खियां वायरस को और अधिक पौधों में फैलाएं',
    'Remove and destroy infected plants if they are severely affected': 'यदि संक्रमित पौधे गंभीर रूप से प्रभावित हों तो उन्हें हटा दें और नष्ट कर दें',
    'Remove any cedar or juniper trees growing near your apple orchard if possible': 'यदि संभव हो तो अपने सेब के बगीचे के पास उगे देवदार या जुनिपर के पेड़ों को हटा दें',
    'Remove badly infected leaves and fruits and destroy them': 'बुरी तरह से संक्रमित पत्तियों और फलों को हटा दें और उन्हें नष्ट कर दें',
    'Remove extra runners regularly to keep energy focused on fruiting': 'फलने-फूलने पर ऊर्जा केंद्रित रखने के लिए अतिरिक्त धावकों को नियमित रूप से हटा दें',
    'Remove infected leaves and burn them — do not leave on the ground': 'संक्रमित पत्तियों को हटा दें और जला दें - जमीन पर न छोड़ें',
    'Remove infected leaves from the base of the plant upward': 'संक्रमित पत्तियों को पौधे के आधार से ऊपर की ओर हटा दें',
    'Remove infected lower leaves and destroy them — do not leave on ground': 'संक्रमित निचली पत्तियों को हटा दें और उन्हें नष्ट कर दें - जमीन पर न छोड़ें',
    'Remove old fruiting canes after harvest each year': 'प्रत्येक वर्ष कटाई के बाद पुराने फलदार गन्नों को हटा दें',
    'Remove older infected leaves from the plant at the base': 'पौधे से पुरानी संक्रमित पत्तियों को आधार से हटा दें',
    'Remove severely infected plants to stop the spread': 'प्रसार को रोकने के लिए गंभीर रूप से संक्रमित पौधों को हटा दें',
    'Repeat spray every 10–14 days if weather stays wet': 'यदि मौसम गीला रहता है तो हर 10-14 दिनों में स्प्रे दोहराएं',
    'Replace old plants that are more than 3 years old with fresh young seedlings': '3 वर्ष से अधिक पुराने पुराने पौधों को ताजा युवा पौधों से बदलें',
    'Report to your local Krishi Vigyan Kendra (KVK) immediately if you suspect this disease': 'यदि आपको इस बीमारी का संदेह है तो तुरंत अपने स्थानीय कृषि विज्ञान केंद्र (KVK) को सूचित करें',
    'Rotate crops every season — alternate with soybean or wheat': 'हर मौसम में फसलें बदलें - सोयाबीन या गेहूं के साथ वैकल्पिक',
    'Rotate crops — do not grow corn in the same field every year': 'फसलें बदलिए - हर साल एक ही खेत में मक्का न उगाएं',
    'Rotate crops — do not grow potato in the same field every year': 'फसलें बदलिए - हर साल एक ही खेत में आलू न उगाएँ',
    "Rotate crops — don't grow tomatoes in the same spot every year": 'फसलें बारी-बारी से उगाएं - हर साल एक ही स्थान पर टमाटर न उगाएं',
    'Rotate tomato with other crops every 2–3 years': 'हर 2-3 साल में टमाटर को अन्य फसलों के साथ बदलें',
    'Rotate with non-legume crops like wheat every year': 'हर साल गेहूँ जैसी गैर-दलहनी फसलें उगाएँ',
    'Rough, scabby patches on the fruit skin': 'फलों की त्वचा पर खुरदुरे, पपड़ीदार धब्बे',
    'Round brown spots with darker rings on leaves': 'पत्तियों पर गहरे रंग के छल्लों वाले गोल भूरे धब्बे',
    'Septoria Leaf Spot': 'सेप्टोरिया लीफ स्पॉट',
    'Severe cases cause leaves to yellow and dry out': 'गंभीर मामलों में पत्तियाँ पीली होकर सूखने लगती हैं',
    'Severe infection causes leaves to drop, exposing fruits to sun damage': 'गंभीर संक्रमण के कारण पत्तियाँ झड़ जाती हैं, जिससे फल धूप से क्षतिग्रस्त हो जाते हैं',
    'Severely affected leaves turn reddish-brown and dry up completely': 'गंभीर रूप से प्रभावित पत्तियां लाल-भूरी हो जाती हैं और पूरी तरह सूख जाती हैं',
    'Severely affected vines may need to be removed completely': 'गंभीर रूप से प्रभावित बेलों को पूरी तरह से हटाने की आवश्यकता हो सकती है',
    'Severely infected leaves dry out completely': 'गंभीर रूप से संक्रमित पत्तियां पूरी तरह सूख जाती हैं',
    'Severely infected leaves fall off, exposing fruits to sunburn and cracking': 'गंभीर रूप से संक्रमित पत्तियाँ झड़ जाती हैं, जिससे फल धूप की चपेट में आ जाते हैं और टूटने लगते हैं',
    'Shrivelled, mummy-like rotted fruits hanging on the tree': 'पेड़ पर लटके हुए, ममी जैसे सड़े हुए फल',
    'Small black dots visible inside the leaf spots': 'पत्ती के धब्बों के अंदर छोटे काले बिंदु दिखाई देते हैं',
    'Small tube-like growths under the leaf': 'पत्ती के नीचे छोटी ट्यूब जैसी वृद्धि',
    'Small water-soaked spots on leaves that turn brown or purple': 'पत्तियों पर पानी से लथपथ छोटे-छोटे धब्बे जो भूरे या बैंगनी रंग के हो जाते हैं',
    'Small, dark brown, water-soaked spots on leaves surrounded by yellow rings': 'पत्तियों पर पीले छल्लों से घिरे छोटे, गहरे भूरे, पानी से लथपथ धब्बे',
    'Small, dark purple spots on upper leaf surface': 'पत्ती की ऊपरी सतह पर छोटे, गहरे बैंगनी रंग के धब्बे',
    'Small, dark, water-soaked spots on leaves': 'पत्तियों पर छोटे, काले, पानी से लथपथ धब्बे',
    'Small, lopsided fruits that stay green even when ripe and taste very bitter': 'छोटे, टेढ़े-मेढ़े फल जो पकने पर भी हरे रहते हैं और स्वाद में बहुत कड़वे होते हैं',
    'Small, oval, reddish-brown raised bumps on both sides of leaves': 'पत्तियों के दोनों ओर छोटे, अंडाकार, लाल-भूरे रंग के उभरे हुए उभार',
    'Soil splashing onto leaves during heavy rain or overhead watering': 'भारी बारिश या ऊपरी पानी के दौरान पत्तियों पर मिट्टी का गिरना',
    'Soybean': 'सोयाबीन',
    'Space plants well so wind can pass through': 'पौधों को अच्छी तरह से जगह दें ताकि हवा आर-पार हो सके',
    'Space plants well — at least 1 metre between plants': 'पौधों को अच्छी तरह से जगह दें - पौधों के बीच कम से कम 1 मीटर की दूरी रखें',
    'Space tomato plants at least 50–60 cm apart': 'टमाटर के पौधों को कम से कम 50-60 सेमी की दूरी पर रखें',
    'Spider Mite Attack': 'मकड़ी घुन का हमला',
    'Spores spread extremely fast through wind and rain — can spread across entire village in days': 'बीजाणु हवा और बारिश के माध्यम से बहुत तेज़ी से फैलते हैं - कुछ ही दिनों में पूरे गाँव में फैल सकते हैं',
    'Spots can also appear on stems and fruits': 'तने और फलों पर भी धब्बे दिखाई दे सकते हैं',
    'Spots can grow 10–15 cm long': 'धब्बे 10-15 सेमी लंबे हो सकते हैं',
    'Spots expand and their centres turn brownish-gray': 'धब्बे फैल जाते हैं और उनके केंद्र भूरे-भूरे रंग के हो जाते हैं',
    "Spots fall out, creating a 'shot-hole' or bullet-hole look on leaves": "धब्बे झड़ जाते हैं, जिससे पत्तियों पर 'शॉट-होल' या बुलेट-होल जैसा दृश्य बन जाता है",
    'Spots may have a yellowish ring around them': 'धब्बों के चारों ओर एक पीले रंग का घेरा हो सकता है',
    'Spots turn brown with yellow rings around them': 'धब्बे भूरे रंग के हो जाते हैं और उनके चारों ओर पीले छल्ले बन जाते हैं',
    'Spray a copper-based fungicide every 7–10 days during wet weather': 'गीले मौसम के दौरान हर 7-10 दिनों में तांबा आधारित कवकनाशी का छिड़काव करें',
    'Spray abamectin, bifenazate, or spiromesifen miticide — these are specific to mites, not normal pesticides': 'एबामेक्टिन, बिफेनाज़ेट, या स्पाइरोमेसिफेन माइटिसाइड का छिड़काव करें - ये घुन के लिए विशिष्ट हैं, सामान्य कीटनाशक नहीं',
    'Spray azoxystrobin or chlorothalonil fungicide': 'एज़ोक्सीस्ट्रोबिन या क्लोरोथालोनिल कवकनाशी का छिड़काव करें',
    'Spray captan or myclobutanil fungicide every 7–10 days': 'हर 7-10 दिनों में कैप्टान या मायक्लोबुटानिल कवकनाशी का छिड़काव करें',
    'Spray captan or thiophanate-methyl fungicide': 'कैप्टान या थियोफैनेट-मिथाइल कवकनाशी का छिड़काव करें',
    'Spray chlorothalonil or mancozeb fungicide': 'क्लोरोथालोनिल या मैंकोजेब फफूंदनाशी का छिड़काव करें',
    'Spray copper before the rainy season as a protective measure': 'सुरक्षात्मक उपाय के रूप में बरसात के मौसम से पहले तांबे का छिड़काव करें',
    'Spray copper hydroxide or copper sulphate bactericide every 7 days': 'हर 7 दिन में कॉपर हाइड्रॉक्साइड या कॉपर सल्फेट जीवाणुनाशक का छिड़काव करें',
    'Spray copper-based bactericide (copper hydroxide or copper sulphate) at the first sign': 'पहले संकेत पर कॉपर आधारित जीवाणुनाशक (कॉपर हाइड्रॉक्साइड या कॉपर सल्फेट) का छिड़काव करें',
    'Spray copper-based bactericide every 7–10 days': 'हर 7-10 दिनों में तांबा आधारित जीवाणुनाशक का छिड़काव करें',
    'Spray during early morning hours for best results': 'सर्वोत्तम परिणामों के लिए सुबह के समय स्प्रे करें',
    'Spray imidacloprid or thiamethoxam insecticide to kill whiteflies on all remaining healthy plants': 'शेष सभी स्वस्थ पौधों पर सफेद मक्खियों को मारने के लिए इमिडाक्लोप्रिड या थियामेथोक्साम कीटनाशक का छिड़काव करें',
    'Spray insecticide regularly every 3 weeks to control psyllid insects': 'साइलीड कीटों को नियंत्रित करने के लिए हर 3 सप्ताह में नियमित रूप से कीटनाशक का छिड़काव करें',
    'Spray mancozeb or azoxystrobin fungicide on leaves': 'पत्तियों पर मैंकोजेब या एज़ोक्सीस्ट्रोबिन फफूंदनाशी का छिड़काव करें',
    'Spray mancozeb or captan fungicide every 7–10 days': 'हर 7-10 दिनों में मैन्कोजेब या कैप्टान कवकनाशी का छिड़काव करें',
    'Spray mancozeb or chlorothalonil fungicide every 7–10 days': 'हर 7-10 दिनों में मैन्कोजेब या क्लोरोथालोनिल कवकनाशी का छिड़काव करें',
    'Spray mancozeb or copper-based fungicide': 'मैंकोजेब या कॉपर आधारित कवकनाशी का छिड़काव करें',
    'Spray mancozeb, chlorothalonil, or copper-based fungicide every 7–10 days': 'हर 7-10 दिनों में मैन्कोज़ेब, क्लोरोथालोनिल, या तांबा आधारित कवकनाशी का छिड़काव करें',
    'Spray mancozeb, propiconazole, or azoxystrobin fungicide': 'मैन्कोजेब, प्रोपिकोनाज़ोल, या एज़ोक्सीस्ट्रोबिन कवकनाशी का छिड़काव करें',
    'Spray myclobutanil or mancozeb fungicide in early spring': 'शुरुआती वसंत में मायक्लोबुटानिल या मैंकोज़ेब कवकनाशी का छिड़काव करें',
    'Spray neem oil every week as a preventive measure against whiteflies': 'सफेद मक्खी से बचाव के उपाय के रूप में हर सप्ताह नीम के तेल का छिड़काव करें',
    'Spray neem oil mixed with water (5 ml per litre) as an organic option': 'जैविक विकल्प के रूप में नीम के तेल को पानी (5 मिली प्रति लीटर) में मिलाकर छिड़काव करें',
    'Spray neem oil once a month as a precaution': 'एहतियात के तौर पर महीने में एक बार नीम के तेल का छिड़काव करें',
    'Spray preventively before the rainy season begins': 'बरसात का मौसम शुरू होने से पहले बचाव के लिए छिड़काव करें',
    'Spray propiconazole or azoxystrobin-based fungicide': 'प्रोपिकोनाज़ोल या एज़ोक्सीस्ट्रोबिन-आधारित कवकनाशी का छिड़काव करें',
    'Spray protective fungicide (mancozeb) at the start of cool/rainy season every year': 'हर साल ठंड/बरसात के मौसम की शुरुआत में सुरक्षात्मक कवकनाशी (मैन्कोज़ेब) का छिड़काव करें',
    'Spray protective fungicide (mancozeb) before the rainy season starts every year': 'हर साल बरसात का मौसम शुरू होने से पहले सुरक्षात्मक कवकनाशी (मैन्कोज़ेब) का छिड़काव करें',
    'Spray wettable sulphur or potassium bicarbonate on affected areas': 'प्रभावित क्षेत्रों पर वेटेबल सल्फर या पोटेशियम बाइकार्बोनेट का छिड़काव करें',
    'Spray wettable sulphur or potassium bicarbonate solution on all leaf surfaces': 'सभी पत्तियों की सतहों पर वेटेबल सल्फर या पोटेशियम बाइकार्बोनेट घोल का छिड़काव करें',
    'Spraying pesticides that kill the natural enemies of mites makes the problem worse': 'घुन के प्राकृतिक शत्रुओं को मारने वाले कीटनाशकों का छिड़काव करने से समस्या और भी बदतर हो जाती है',
    'Spread by tiny jumping insects called psyllids that suck sap and carry the disease': 'साइलिड्स नामक छोटे उछल-कूद करने वाले कीड़ों द्वारा फैलता है जो रस चूसते हैं और रोग फैलाते हैं',
    'Spread by whitefly insects that carry the virus from sick plants to healthy ones': 'सफ़ेद मक्खी कीड़ों द्वारा फैलता है जो वायरस को बीमार पौधों से स्वस्थ पौधों तक ले जाते हैं',
    'Spreads very easily by touching infected plants then healthy ones with bare hands': 'संक्रमित पौधों और फिर स्वस्थ पौधों को नंगे हाथों से छूने से बहुत आसानी से फैलता है',
    'Squash / Pumpkin / Gourd': 'स्क्वैश/कद्दू/लौकी',
    'Stake plants to keep leaves and fruits off the ground': 'पत्तियों और फलों को ज़मीन से दूर रखने के लिए पौधों को बाँधें',
    'Stake plants to keep them upright and leaves off the ground': 'पौधों को सीधा रखें और पत्तियों को जमीन से ऊपर रखें',
    'Stake plants when they are young before they start falling over': 'पौधों के गिरने से पहले उन्हें बचपन में ही दांव पर लगा दें',
    "Stake plants when they are young so they don't bend and break": 'जब पौधे छोटे हों तो उन्हें दाँव पर लगाएँ ताकि वे झुकें या टूटें नहीं',
    'Start preventive fungicide sprays before the flowering stage': 'फूल आने की अवस्था से पहले निवारक कवकनाशी स्प्रे शुरू करें',
    'Start spraying early when first spots appear': 'जब पहले धब्बे दिखाई दें तो जल्दी छिड़काव शुरू करें',
    'Stems turn dark brown and collapse': 'तने गहरे भूरे रंग के हो जाते हैं और गिर जाते हैं',
    'Stop all overhead watering immediately — switch to watering at the base only': 'सभी ऊपरी पानी को तुरंत बंद कर दें - केवल आधार पर पानी देना शुरू करें',
    'Strawberry': 'स्ट्रॉबेरी',
    'Stunted and weak new growth': 'अवरुद्ध और कमज़ोर नई वृद्धि',
    'Sunken dark spots on fruits': 'फलों पर धँसे हुए काले धब्बे',
    'Support canes with stakes or wires to prevent bending and breakage': 'झुकने और टूटने से बचाने के लिए बेंतों को खूँटों या तारों से सहारा दें',
    'Tan or brown spots with dark edges on leaves': 'पत्तियों पर गहरे किनारों वाले भूरे या भूरे रंग के धब्बे',
    'Target Spot': 'लक्ष्य स्थान',
    'There is NO cure once a plant is infected with the virus': 'एक बार जब कोई पौधा वायरस से संक्रमित हो जाता है तो उसका कोई इलाज नहीं होता है',
    'There is NO cure — infected trees MUST be removed and burned far away to protect other trees': 'इसका कोई इलाज नहीं है - अन्य पेड़ों की सुरक्षा के लिए संक्रमित पेड़ों को हटा देना चाहिए और दूर जला देना चाहिए',
    'Thin fruits when young so remaining fruits grow bigger and sweeter': 'छोटे होने पर फल पतले होते हैं इसलिए शेष फल बड़े और मीठे होते हैं',
    'Thin spider-like webs visible under leaves when you look closely': 'ध्यान से देखने पर पत्तियों के नीचे मकड़ी जैसे पतले जाले दिखाई देते हैं',
    'Tiger-stripe pattern — yellow and brown strips on leaves': 'बाघ-धारी पैटर्न - पत्तियों पर पीली और भूरे रंग की धारियाँ',
    'Till the soil after harvest to destroy infected crop remains': 'कटाई के बाद मिट्टी में संक्रमित फसल को नष्ट करने तक अवशेष रह जाते हैं',
    'Tiny dark specks visible inside each spot': 'प्रत्येक स्थान के अंदर छोटे-छोटे काले धब्बे दिखाई देते हैं',
    'Tiny spider-like creatures (too small to see clearly) that suck sap from leaves, causing them to look bronzed, dusty, and weak. They are not a fungus — they are pests.': 'छोटे मकड़ी जैसे जीव (स्पष्ट रूप से देखने में बहुत छोटे) जो पत्तियों से रस चूसते हैं, जिससे वे कांस्य, धूल भरे और कमजोर दिखते हैं। वे कवक नहीं हैं - वे कीट हैं।',
    'Tomato': 'टमाटर',
    'Too many plants crowded together with poor airflow': 'खराब वायु प्रवाह के कारण बहुत सारे पौधे एक साथ जमा हो गए',
    'Train vines to keep leaves dry with good airflow': 'अच्छे वायु प्रवाह के साथ पत्तियों को सूखा रखने के लिए बेलों को प्रशिक्षित करें',
    'Treat seeds with rhizobium bacteria before sowing for better nitrogen fixation': 'बेहतर नाइट्रोजन स्थिरीकरण के लिए बुआई से पहले बीजों को राइजोबियम बैक्टीरिया से उपचारित करें',
    'Tree slowly declines and stops producing over years': 'पेड़ धीरे-धीरे नष्ट हो जाता है और वर्षों में उत्पादन बंद कर देता है',
    'Try to preserve natural predators by not overspraying pesticides unnecessarily': 'अनावश्यक रूप से कीटनाशकों का अधिक छिड़काव न करके प्राकृतिक शिकारियों को संरक्षित करने का प्रयास करें',
    'Tubers underground develop brown rot inside': 'भूमिगत कंदों के अंदर भूरे रंग की सड़न विकसित हो जाती है',
    'Use certified disease-free seed potatoes': 'प्रमाणित रोगमुक्त बीज आलू का प्रयोग करें',
    'Use certified disease-resistant corn seeds': 'प्रमाणित रोग प्रतिरोधी मक्के के बीज का प्रयोग करें',
    'Use drip irrigation at the base — never sprinkler on leaves': 'आधार पर ड्रिप सिंचाई का उपयोग करें - पत्तियों पर कभी भी छिड़काव न करें',
    'Use drip irrigation — never overhead sprinklers on tomatoes': 'ड्रिप सिंचाई का उपयोग करें - टमाटर पर कभी भी ओवरहेड स्प्रिंकलर न लगाएं',
    'Use mancozeb or captan spray as soon as spots appear': 'धब्बे दिखाई देते ही मैंकोजेब या कैप्टान स्प्रे का प्रयोग करें',
    'Use mold-resistant tomato varieties for enclosed farming': 'बंद जगह में खेती के लिए फफूंद प्रतिरोधी टमाटर की किस्मों का उपयोग करें',
    'Use straw mulch under plants to keep fruits clean and soil moist': 'फलों को साफ और मिट्टी को नम रखने के लिए पौधों के नीचे पुआल गीली घास का प्रयोग करें',
    'Very few or absolutely no fruits form': 'बहुत कम या बिल्कुल भी फल नहीं बनते हैं',
    'Very high humidity — especially above 85%': 'बहुत अधिक आर्द्रता - विशेष रूप से 85% से ऊपर',
    'Warm and humid weather': 'गर्म और आर्द्र मौसम',
    'Warm and humid weather conditions': 'गर्म और आर्द्र मौसम की स्थिति',
    'Warm and wet weather conditions': 'गर्म और आर्द्र मौसम की स्थिति',
    'Warm and wet weather during the growing season': 'बढ़ते मौसम के दौरान गर्म और गीला मौसम',
    'Warm and wet weather in spring and early summer': 'वसंत और गर्मियों की शुरुआत में गर्म और गीला मौसम',
    'Warm temperatures (24–29°C) with high humidity': 'उच्च आर्द्रता के साथ गर्म तापमान (24-29 डिग्री सेल्सियस)।',
    'Warm, humid weather during the growing season': 'बढ़ते मौसम के दौरान गर्म, आर्द्र मौसम',
    'Warm, humid, wet conditions during the growing season': 'बढ़ते मौसम के दौरान गर्म, आर्द्र, गीली स्थितियाँ',
    'Warm, wet, rainy weather conditions': 'गर्म, गीला, बरसाती मौसम की स्थिति',
    'Wash hands thoroughly with soap and disinfect tools with bleach water before touching other plants': 'अन्य पौधों को छूने से पहले हाथों को साबुन से अच्छी तरह धोएं और ब्लीच वाले पानी से उपकरणों को कीटाणुरहित करें',
    'Wash the undersides of leaves with a strong water spray to physically knock mites off': 'घुन को भगाने के लिए पत्तों के निचले हिस्से को तेज पानी के स्प्रे से धोएं',
    'Water at the base of the plant in the morning — never in the evening': 'पौधे की जड़ में सुबह पानी दें - शाम को कभी नहीं',
    'Water at the base only — never from above': 'पानी केवल आधार पर - ऊपर से कभी नहीं',
    'Water at the base only — never spray water onto leaves': 'पानी केवल आधार पर लगाएं - कभी भी पत्तियों पर पानी न छिड़कें',
    'Water at the base only — not on leaves or fruits': 'पानी केवल आधार पर - पत्तियों या फलों पर नहीं',
    'Water at the base, not by sprinkling on leaves': 'पानी पत्तों पर छिड़क कर नहीं, बल्कि आधार पर लगाएं',
    'Water at the base, not on leaves': 'पानी आधार पर दें, पत्तियों पर नहीं',
    'Water consistently at the base — avoid wetting leaves or fruits': 'आधार पर लगातार पानी दें - पत्तियों या फलों को गीला करने से बचें',
    'Water in the morning so leaves dry during the day': 'सुबह पानी दें ताकि दिन के दौरान पत्तियाँ सूख जाएँ',
    'Water only at the base — never from above': 'पानी केवल आधार पर - ऊपर से कभी नहीं',
    'Water plants regularly — mites multiply fast in dry conditions': 'पौधों को नियमित रूप से पानी दें - शुष्क परिस्थितियों में घुन तेजी से बढ़ते हैं',
    'Water regularly but avoid waterlogging': 'नियमित रूप से पानी दें लेकिन जलभराव से बचें',
    'Water splashing from soil up onto leaves during rain or watering': 'बारिश या सिंचाई के दौरान मिट्टी से पत्तियों पर पानी का छींटा पड़ना',
    'Water staying on leaves for too long': 'पानी का पत्तों पर बहुत देर तक रुकना',
    'Wet and humid weather during the growing season': 'बढ़ते मौसम के दौरान गीला और आर्द्र मौसम',
    'Wet and humid weather for many continuous days': 'लगातार कई दिनों तक गीला और आर्द्र मौसम',
    'Wet and rainy weather in spring': 'वसंत ऋतु में गीला और बरसात का मौसम',
    'Wet and windy spring weather helps spread it': 'गीला और तेज़ हवा वाला वसंत का मौसम इसे फैलाने में मदद करता है',
    'Wet weather and high humidity during the season': 'मौसम के दौरान गीला मौसम और उच्च आर्द्रता',
    'White fuzzy mould growth at the edge of spots on the underside of leaves (seen in early morning)': 'पत्तियों के नीचे की ओर धब्बों के किनारे पर सफेद रोयेंदार फफूंद की वृद्धि (सुबह में देखी गई)',
    'White fuzzy mould ring visible at the edge of spots (usually early morning)': 'धब्बों के किनारे पर सफेद फजी साँचे की अंगूठी दिखाई देती है (आमतौर पर सुबह के समय)',
    'White powdery coating on the top surface of leaves': 'पत्तियों की ऊपरी सतह पर सफेद चूर्ण जैसा लेप',
    'White powdery patches on leaves — especially young ones': 'पत्तियों पर सफेद पाउडर जैसे धब्बे - विशेषकर युवा पत्तियों पर',
    'Whole leaves may die in severe cases': 'गंभीर मामलों में पूरी पत्तियाँ मर सकती हैं',
    'Wind and rain splashing bacteria from plant to plant rapidly': 'हवा और बारिश से बैक्टीरिया तेजी से पौधे से पौधे तक फैल रहे हैं',
    'Wind and rain spreading bacteria from plant to plant': 'हवा और बारिश बैक्टीरिया को पौधे से पौधे तक फैला रही है',
    'Wind carrying fungal spores from other fields': 'अन्य क्षेत्रों से फफूंद बीजाणुओं को लाने वाली हवा',
    'Yellow Leaf Curl Virus': 'पीली पत्ती मोड़ने वाला विषाणु',
    'Yellow area around each spot': 'प्रत्येक स्थान के आसपास पीला क्षेत्र',
    'Yellow area surrounding the spots': 'धब्बों के आसपास का पीला क्षेत्र',
    'Your apple plant looks healthy! No signs of disease detected. Keep up the good farming practices.': 'आपका सेब का पौधा स्वस्थ दिख रहा है! रोग का कोई लक्षण नहीं पाया गया। खेती के अच्छे तरीके अपनाएँ।',
    'Your blueberry plant is perfectly healthy! Keep doing what you are doing.': 'आपका ब्लूबेरी पौधा बिल्कुल स्वस्थ है! आप जो कर रहे हैं उसे करते रहें।',
    'Your cherry plant is in good health. No disease found.': 'आपका चेरी का पौधा अच्छे स्वास्थ्य में है। कोई रोग नहीं पाया गया.',
    'Your corn crop looks healthy and growing well! No disease signs found.': 'आपकी मक्के की फसल स्वस्थ और अच्छी तरह से बढ़ती हुई दिख रही है! कोई बीमारी के लक्षण नहीं मिले।',
    'Your grapevine is looking healthy! No disease signs detected.': 'आपकी अंगूर की बेल स्वस्थ दिख रही है! कोई रोग लक्षण नहीं पाया गया।',
    'Your peach tree looks great and healthy!': 'आपका आड़ू का पेड़ बहुत अच्छा और स्वस्थ दिखता है!',
    'Your pepper plant is healthy and looking good!': 'आपका काली मिर्च का पौधा स्वस्थ और अच्छा दिख रहा है!',
    'Your potato crop is growing well with no disease signs. Keep monitoring regularly.': 'आपकी आलू की फसल बिना किसी बीमारी के लक्षण के अच्छी तरह से बढ़ रही है। नियमित रूप से निगरानी करते रहें.',
    'Your raspberry plants are healthy and growing well!': 'आपके रास्पबेरी पौधे स्वस्थ हैं और अच्छी तरह बढ़ रहे हैं!',
    'Your soybean crop looks perfectly healthy!': 'आपकी सोयाबीन की फसल बिल्कुल स्वस्थ दिख रही है!',
    'Your strawberry plants look fresh and healthy!': 'आपके स्ट्रॉबेरी के पौधे ताज़ा और स्वस्थ दिख रहे हैं!',
    'Your tomato plant looks healthy and growing well. Excellent work!': 'आपका टमाटर का पौधा स्वस्थ और अच्छी तरह से विकसित होता हुआ दिख रहा है। उत्कृष्ट कार्य!',
    '⚠️ SPRAY WITHIN 24 HOURS — use metalaxyl + mancozeb (sold as Ridomil Gold) or cymoxanil immediately': '⚠️ 24 घंटे के भीतर स्प्रे करें - मेटालेक्सिल + मैनकोजेब (रिडोमिल गोल्ड के रूप में बेचा जाता है) या सिमोक्सानिल का तुरंत उपयोग करें',
    '⚠️ URGENT — spray metalaxyl + mancozeb (Ridomil Gold) or cymoxanil TODAY — within 24 hours': '⚠️ अत्यावश्यक - मेटालैक्सिल + मैन्कोजेब (रिडोमिल गोल्ड) या सिमोक्सानिल का आज ही छिड़काव करें - 24 घंटों के भीतर'
}
